### ISSUE TITLE
[Question] - When deleting a space, make auto trim()

### ISSUE THREAD

**Issue by GuilhE** [RedMadRobot/input-mask-android#100]
### Prerequisites

* [X] Put an `X` between the brackets on this line if you have done all of the following:
  * read our [Wiki](https://github.com/RedMadRobot/input-mask-android/wiki);
  * read the entire [Known issues](https://github.com/RedMadRobot/input-mask-android#knownissues) section;
  * checked that my feature request isn't already [filled](https://github.com/RedMadRobot/input-mask-android/issues);
  * searched StackOverflow's [`input-mask`](https://stackoverflow.com/questions/tagged/input-mask) tag for similar problems.

### Summary
When deleting text auto trim() (this can be optional)

### Motivation
Achieve the same functionality when typing.

### Describe the solution you'd like
If our mask is [000] [000], when we type the fourth char this lib will automatically put a space and insert the 4th char after it. When deleting this behaviour could be similar, for instance, when deleting the 4th char it could also delete the space.

### Describe alternatives you've considered
```
private const val PHONE_MASK = "[000] [000] [000]"
android:digits="0123456789 "
android:inputType="number|phone"
```

- I've tried to manually achieve this (with another listener) but it will fail with `java.lang.IndexOutOfBoundsException: setSpan (N … N) ends beyond length ...`
- Tried to remove the space char from `digits` and `listener.autocomplete = true` but it also fails with  `java.lang.IndexOutOfBoundsException: setSpan (4 ... 4) ends beyond length 3`

**Comment by taflanidi** [comment]
Hey @GuilhE!
Thanks for your feature request.

I'll have a look, it seems plausible.

**Comment by GuilhE** [comment]
Thanks for your time and interest @taflanidi , just do add 2 notes:

1. It would be nice to have it also on iOS
2. If you point me into the right direction, maybe I could give a hand (on Android)

**Comment by taflanidi** [comment]
@GuilhE, 
Sure, all the new features automagically migrate between the platforms.

In fact, I know there's a couple of wrapper libraries for React Native, Xamarin and other cross-platform SDKs depending on us, and it would be highly inconvenient for them to have different sets of features across the platforms.

Thanks a lot for your suggestion to help. I'm still to make the design decision though, so please equip some additional patience. 

ETA for this feature is this weekend.

**Comment by taflanidi** [comment]
Alright, so I've got an update for you (-:

You might be wondering what's so special about adding a simple `.trim()` call that requires me to think about the decision design so long.

Well, the outcome of your feature request is actually going to bring a highly anticipated feature, which allows not only to trim those pesky whitespaces, but also to remove any formatting characters.

For instance, imagine you have a mask like `[000]-#-[000]`. 
A basic `.trim()` call won't help removing that `-#-` thingy in the middle when you hit `Backspace`, but this new feature will.

Like this:
```
123-#-456
123-#-45
123-#-4
123
12
1
```

The implementation is almost complete. I had had to apply some necessary refactoring here and there, and I've got to make sure all the tests remain green. 

An update is on its way to be published this Monday.

**Comment by GuilhE** [comment]
Thanks for your time and feature :)

**Comment by taflanidi** [comment]
`v.6` is out.

From now, you can

```kotlin
listener.autoskip = true
```

**Comment by TeoCat** [comment]
But does it work for android:inputType="number" only?
