### ISSUE TITLE
Prefix always shows up in editext before even requesting focus.

### ISSUE THREAD

**Issue by chnouman** [RedMadRobot/input-mask-android#102]
I'm trying to add prefix of + in my edittext. 

What I have done is:

```
 installOn(
                addNewNumberTV,
                "+[000] [000] [000] [000]",
                object : ValueListener {
                    override fun onTextChanged(maskFilled: Boolean, @NonNull extractedValue: String, @NonNull formattedValue: String) {
                        Log.d("TAG", extractedValue)
                        Log.d("TAG", maskFilled.toString())
                    }
                }
        )
```

Now when I run the app It shows +. What I want is to show the hint only and when the user press on the edittext then only add the prefix.

**Comment by taflanidi** [comment]
Hey @chnouman!
Thanks for your question.

Have you tried manually making an instance of the `MaskedTextChangedListener` and then manually adding it as a `TextChangedListener` instead of calling the `installOn(…)` method?

Like so:

```kotlin
val listener = MaskedTextChangedListener(
  primaryFormat,
  affineFormats,
  customNotations,
  affinityCalculationStrategy,
  autocomplete,
  autoskip,
  editText,
  listener,
  valueListener
)
editText.addTextChangedListener(listener)
```

**Comment by chnouman** [comment]
I used installOn(...) but the difference was I was attaching FocusChangeListener after installOn(...). This was causing the issue on my side. Now I have dig into your code and added a new callback with installOn for get onFocus call.

**Comment by deepak786** [comment]
When you use installOn, it will add the focus listener on the editText.
So to avoid that use instance of MaskedTextChangeListsner and add the text change listener manually as described here https://github.com/RedMadRobot/input-mask-android/issues/102#issuecomment-608009830
