### ISSUE TITLE
Input character replacing mask patter characters. Is it possible to do, or add as new feature?

### ISSUE THREAD

**Issue by michzio** [RedMadRobot/input-mask-android#103]
Can I have full mask displayed while typing input like (_ _ _)  _ _ _-_ _ _ _

and when typing have (12_) _ _ _ - _ _ _  _
instead of just (12 

and new char is replacing mask character?

**Comment by michzio** [comment]
I've experimented a little bit with the code and it seems that I we want to have this placeholder characters visible we need to 

in Mask.apply(text: CaretString): Result 

at the end of method add one line before returning Result 

modifiedString = this.appendPlaceholder(state, modifiedString)

        return Result(
            CaretString(
                modifiedString,
                modifiedCaretPosition,
                text.caretGravity
            ),
            extractedValue,
            affinity,
            this.noMandatoryCharactersLeftAfterState(state)
        )
    }

this one line could be conditional in some if statement wether we want this feature or not

More over I want to have underscores instead of 00 in placeholder so here I make up solution to add placholderCharacter param to Mask constructor which is optional and then use it in appendPlaceholder method where there are placeholder characters appended like

 is OptionalValueState.StateType.Numeric -> {
                    this.appendPlaceholder(state.child, placeholder + (**placeholderCharacter** ?: "0"))
                }

**Comment by taflanidi** [comment]
Hey @michzio!
Thanks for your question.

Since you've deleted the feature request template text without reading it, I'll just copy-paste the important paragraph in here:

> * [ ] Put an `X` between the brackets on this line if you have done all of the following:
>   * read our [Wiki](https://github.com/RedMadRobot/input-mask-android/wiki);
>   * read the entire [Known issues](https://github.com/RedMadRobot/input-mask-android#knownissues) section;
>   * checked that my feature request isn't already [filled](https://github.com/RedMadRobot/input-mask-android/issues);
>   * searched StackOverflow's [`input-mask`](https://stackoverflow.com/questions/tagged/input-mask) tag for similar problems.

Now please go ahead and check out #75 and #89, thank you.
