### ISSUE TITLE
Is there a way to accept text of A-Z and spaces?

### ISSUE THREAD

**Issue by bobhannahsa** [RedMadRobot/input-mask-android#110]
Hello,

Perhaps i am missing something from the info presented, but i am unable to find a mask that works for alpha cracters i.e. A to Z and also accepts spaces.

I find that if i set the text programmatically in an Android app, that a mask of "[AAAaaa"] accepts space characters if i use the control's .setText method

however if i try to type this entry, using the soft keyboard, then the space character is not supported i.e. no space appears in the text.

My questions are therefore:
1. Does the 'A' or 'a' mask allow for typed spaces?
2. Or how should we define a mask that will accept typed alpha and typed space characters?

Note - the spaces could appear at different points, so a fixed space character at a certain point is not an option in this use case.

**Comment by mateusdamata** [comment]
Hello, you may use [-----]. This way accept spaces and alphanumerics

**Comment by AnnaCarolinaWGC** [comment]
Hi, the spaces don't work on mine when i use [-----]...
