### ISSUE TITLE
Migrate to Maven Central

### ISSUE THREAD

**Issue by GuilhE** [RedMadRobot/input-mask-android#112]
JFrog just announced that they'll be shutting down JCenter:
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Key dates are:

- February 28th: No more submissions will be accepted to Bintray, JCenter
- May 1st: Bintray, JCenter services will no longer be available

Hence, input-mask-android should also be migrated to another maven repository like Maven central.

**Comment by taflanidi** [comment]
No shit.

**Comment by GuilhE** [comment]
[This](https://getstream.io/blog/publishing-libraries-to-mavencentral-2021/) will also help.

**Comment by taflanidi** [comment]
More news 

https://twitter.com/gradle/status/1357766534370893832?s=20

**Comment by GuilhE** [comment]
[Migrating old artifacts from JCenter to MavenCentral](https://www.marcogomiero.com/posts/2021/move-libray-jcenter-to-maven/)

**Comment by ildar2** [comment]
any updates? only one month left

**Comment by xandr08** [comment]
Hi there! We want to remove jcenter() from our project. 
When are you planning to migrate to maven?
Thanks for the library)

**Comment by taflanidi** [comment]
Hey.

The migration is in progress. I haven't had much time, unfortunately, but still I'd like to finish up this weekend.

**Comment by ozbek** [comment]
> The migration is in progress. I haven't had much time, unfortunately, but still I'd like to finish up this weekend.

Migration to JitPack seems to require a lot less effort (in case _this_ weekend is still not around:).

**Comment by davidmigloz** [comment]
You can already use it in JitPack there's nothing to migrate:
https://jitpack.io/#RedMadRobot/input-mask-android

**Comment by ozbek** [comment]
That's right, albeit with a different group ID.

**Comment by netmaxt3r** [comment]
use below snippet in your toplevel `build.gradle` to substitute dependency to jitpack repo. In my case on react-native project I didnt want to patch the npm package

```gradle
allprojects {
    repositories {
        maven {
            url 'https://jitpack.io'
        }
    }
    configurations.all {
        resolutionStrategy {
            dependencySubstitution {
                substitute module("com.redmadrobot:input-mask-android:6.0.0") using module('com.github.RedMadRobot:input-mask-android:6.0.0')
            }
        }
    }
}
```

**Comment by carstenhag** [comment]
Hello there, is there an update on this? Android Studio Arctiv Fox & AGP 7.0 just got released, so there's even more urgency to remove jCenter :)

**Comment by jpteruel095** [comment]
Any recent updates? I'm trying to use this library called 'moko-widgets' (https://github.com/icerockdev/moko-widgets)
And I'm here because I'm encountering issues about this library not being available on mavenCentral.

> use below snippet in your toplevel `build.gradle` to substitute dependency to jitpack repo. In my case on react-native project I didnt want to patch the npm package
> 
> ```groovy-gradle
> allprojects {
>     repositories {
>         maven {
>             url 'https://jitpack.io'
>         }
>     }
>     configurations.all {
>         resolutionStrategy {
>             dependencySubstitution {
>                 substitute module("com.redmadrobot:input-mask-android:6.0.0") using module('com.github.RedMadRobot:input-mask-android:6.0.0')
>             }
>         }
>     }
> }
> ```

For kotlin dsl people, I'm using this:
```
allprojects {
    repositories {
        google()
        mavenCentral()
        maven(url = "https://jitpack.io")
    }
    configurations.all {
        resolutionStrategy {
            dependencySubstitution {
                substitute(
                    module("com.redmadrobot:input-mask-android:6.0.0")
                ).using(module("com.github.RedMadRobot:input-mask-android:6.0.0"))
            }
        }
    }
}
```

**Comment by sezginriggs** [comment]
any recent updates? we had this problem: https://github.com/react-native-text-input-mask/react-native-text-input-mask/issues/252

**Comment by taflanidi** [comment]
Closing.

Please refer to the PSA.

**Comment by ozbek** [comment]
JitPack FTW!

**Comment by s-fedosov** [comment]
jitpack is down.
