### ISSUE TITLE
Wrong truncation when pasting phone number

### ISSUE THREAD

**Issue by DarkMinstrel** [RedMadRobot/input-mask-android#113]
I have a phone number mask like this:
+555 [00] [000] [00] [00]

User wants to paste the number in full national format, for example "+555123456789"
The expected input after paste would be:
+555 12 345 67 89
But the actual input is:
+555 55 512 34 56

So in case of phone numbers, the library should probably truncate the prefix and fill in the 9 last digits of clipboard text.

**Comment by taflanidi** [comment]
Going to look into this, thanks.

**Comment by taflanidi** [comment]
Please update to the latest lib version, we've got this cured.
