### ISSUE TITLE
affineFormats конфликтуют.

### ISSUE THREAD

**Issue by RandGor** [RedMadRobot/input-mask-android#116]
Использую affineFormats для ввода серийных номеров. 
Есть основной формат "[A] [000] [AA] [00]". 
Есть дополнительный affineFormats "[A][0000] [00]".

Без лишних манипуляций дополнительный ввести просто невозможно. Перепробовал все сочетания `affinityCalculationStrategy`, но ни один не позволил решить задачу.

Пользователю приходится добавлять и убирать пробел, являющийся вторым символом в этой строке, и только в таком случае он может переключаться между форматами.

Вопрос: возможно ли сделать такое автоматическое переключение между масками силами данной либы?

**Comment by RandGor** [comment]
Пример кода. В остальном коде нет get/set обращений к myEditText.text. Либа используется по-сути больше с эстетической точки зрения, а также для удобства юзера.
```
MaskedTextChangedListener.installOn(
        editText = myEditText,
        primaryFormat = "[A] [000] [AA] [00]",
        affineFormats = listOf("[A][0000] [00]"),
        affinityCalculationStrategy = AffinityCalculationStrategy.WHOLE_STRING,
        customNotations = listOf(),
    ) { _, extractedValue, _ ->
        //передача extractedValue в vm
    }
```

**Comment by RandGor** [comment]
В качестве myEditText служит простой TextInputEditText:

```
        <com.google.android.material.textfield.TextInputEditText
            android:id="@+id/myEditText"
            android:saveEnabled="false"
            android:singleLine="true" />
```

**Comment by taflanidi** [comment]
Привет @RandGor 
Обидный затык. `AffinityCalculationStrategy.EXTRACTED_VALUE_CAPACITY` должна бы решать этот вопрос, но видимо нет.

Я гляну, как проще всего вылечить.

**Comment by RandGor** [comment]
Привет @taflanidi 
Спасибо! Вроде как удалось решить проблему, поработав с настройками:
```
        affinityCalculationStrategy = AffinityCalculationStrategy.WHOLE_STRING,
        autocomplete = false,
        autoskip = true,
```
Теперь выбранная маска меняется автоматически, как и было задумано. issue можно закрывать.
Ещё раз большое спасибо за Quick Response :)

**Comment by taflanidi** [comment]
@RandGor понял, принял.

Я всё-таки протыкаю этот кейс. Есть вероятность, что это ожидаемое поведение. Если это так, найду первопричину, и можно будет подумать в сторону расширения библиотеки, чтобы не приходилось заветную комбинацию подбирать. 

Если это не ожидаемое поведение — починю.

Пока не закрываю.

**Comment by taflanidi** [comment]
Да, увы, алгоритм всё считает правильно, и самое простое, что можно сделать — отключить `autocomplete`, чтобы первый пробел самостоятельно не вставлялся. Думаю, потеря невелика.
