### ISSUE TITLE
Could not find com.redmadrobot:input-mask-android:6.0.0

### ISSUE THREAD

**Issue by carolinaknoll** [RedMadRobot/input-mask-android#120]
### Prerequisites

* [X] Put an `X` between the brackets on this line if you have done all of the following:
  * read our [Wiki](https://github.com/RedMadRobot/input-mask-android/wiki);
  * read the entire [Known issues](https://github.com/RedMadRobot/input-mask-android#knownissues) section;
  * checked that my issue isn't already [filled](https://github.com/RedMadRobot/input-mask-android/issues?q=is%3Aissue);
  * searched StackOverflow's [`input-mask`](https://stackoverflow.com/questions/tagged/input-mask) tag for similar problems.

### Describe the bug
I am unable to install the library because **jcenter** seems to be offline and it seems that this library is not available on maven repository or other sources. Can it be added in other sources to not depend solely on jcenter?

### Steps to reproduce the behaviour:

1. Have a `react-native` project with [react-native-text-input-mask](https://github.com/react-native-text-input-mask/react-native-text-input-mask) as a dependency
2. Run `react-native run-android`

**Expected behaviour**
No errors are shown while downloading dependencies and the emulator or build runs successfully. 

**Actual behaviour**

When running `react-native run-android`, it is unable to download the dependency and I get the error:

```
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.redmadrobot:input-mask-android:6.0.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/redmadrobot/input-mask-android/6.0.0/input-mask-android-6.0.0.pom
       - https://repo.maven.apache.org/maven2/com/redmadrobot/input-mask-android/6.0.0/input-mask-android-6.0.0.pom
       - https://repo1.maven.org/maven2/com/redmadrobot/input-mask-android/6.0.0/input-mask-android-6.0.0.pom
       - file:/Users/user/.m2/repository/com/redmadrobot/input-mask-android/6.0.0/input-mask-android-6.0.0.pom
```

**Comment by osipxd** [comment]
Starting from 6.0.0, input-mask publication was migrated to jitpack.io and its coordinates was changed.
Please, read [this section](https://github.com/RedMadRobot/input-mask-android#gradle) of the docs.

**Comment by carolinaknoll** [comment]
Ah, I see! This part of the documentation had no mention to jcenter, so I had overlooked it. 

Sorry about that, and thanks for your fast reply and for pointing me in the right direction.
