### ISSUE TITLE
Could not resolve com.redmadrobot:inputmask:4.1.0

### ISSUE THREAD

**Issue by stereodenis** [RedMadRobot/input-mask-android#125]
> Could not resolve com.redmadrobot:inputmask:4.1.0.
     Required by:
         project :app > project :azsgomodule
      > Could not resolve com.redmadrobot:inputmask:4.1.0.
         > Could not get resource 'https://jitpack.io/com/redmadrobot/inputmask/4.1.0/inputmask-4.1.0.pom'.
            > Could not GET 'https://jitpack.io/com/redmadrobot/inputmask/4.1.0/inputmask-4.1.0.pom'. Received status code 401 from server: Unauthorized

**Comment by osipxd** [comment]
Try `com.redmadrobot:input-mask-android` instead of `com.redmadrobot:inputmask`
