### ISSUE TITLE
Repair JetPack Builds

### ISSUE THREAD

**Issue by taflanidi** [RedMadRobot/input-mask-android#129]
### Prerequisites

* [x] Put an `X` between the brackets on this line if you have done all of the following:
  * read our [Wiki](https://github.com/RedMadRobot/input-mask-android/wiki);
  * read the entire [Known issues](https://github.com/RedMadRobot/input-mask-android#knownissues) section;
  * checked that my issue isn't already [filled](https://github.com/RedMadRobot/input-mask-android/issues?q=is%3Aissue);
  * searched StackOverflow's [`input-mask`](https://stackoverflow.com/questions/tagged/input-mask) tag for similar problems.

### Describe the bug
See https://jitpack.io/com/github/RedMadRobot/input-mask-android/7.1.1/build.log

### Steps to reproduce the behaviour:

1. Publish

**Expected behaviour**
Builds an artefact, the artefact gets published.

**Actual behaviour**
Build fails

**Comment by osipxd** [comment]
AGP requires Java 11 target [starting from 7.4](https://developer.android.com/build/releases/past-releases/agp-7-4-0-release-notes#jvm-11-bytecode).
