### ISSUE TITLE
Custom countries list for PhoneInputListener

### ISSUE THREAD

**Issue by schnaps1981** [RedMadRobot/input-mask-android#130]
### Prerequisites

* [X ] Put an `X` between the brackets on this line if you have done all of the following:
  * read our [Wiki](https://github.com/RedMadRobot/input-mask-android/wiki);
  * read the entire [Known issues](https://github.com/RedMadRobot/input-mask-android#knownissues) section;
  * checked that my issue isn't already [filled](https://github.com/RedMadRobot/input-mask-android/issues?q=is%3Aissue);
  * searched StackOverflow's [`input-mask`](https://stackoverflow.com/questions/tagged/input-mask) tag for similar problems.

### Describe the bug
если установить кастомный список масок, то ввод номера телефона по маске не работает.

если я правильно понял, что если проинициализировать свойство customCountries списком типа Country, то для формирования маски будет использоваться значение этого свойства, вместо Country::all

Но в классе Country есть методо findCountries, который вычисляет подходящие маски, основываясь на текущем вводе. Так вот этот метод производит поиск масок только если customCountries равен null 

![изображение](https://user-images.githubusercontent.com/34050116/235860095-96b66aa1-79d2-4c9a-9cea-faaca1ce1ed0.png)

или я неправильно понял, как работает кастомный список?

**Comment by taflanidi** [comment]
Вот чорт, я забыл скобки :D 

Конечно же, должно быть

```kotlin
return (customCountries ?: all).filter { …
```

Спасибо за рапорт, дефект устраню на выходных (-:

**Comment by taflanidi** [comment]
Done 🚀

P.S. Список всех стран можно и нужно расширять и шатать. Я в одно лицо не скоро втащу все мировые форматы номеров телефонов, feel free to send your pull requests :D

**Comment by schnaps1981** [comment]
добро! как сделаю, проверю на проде ))), пришлю несколько стран снг, которых нет в all ))
