### ISSUE TITLE
The issue with doubling

### ISSUE THREAD

**Issue by Azarnoyz** [RedMadRobot/input-mask-android#131]
I am trying with phone masks "+7 ([000]) [000]-[00]-[00]" and "([00]) [000]-[00]-[00]"
in the first case when I entered the first digit 0, I got 00 in the second case doubling was after ) for example (23) 00 but I entered just one 0

**Comment by taflanidi** [comment]
I'd kindly ask you to follow the bug report template; otherwise, I'm closing this ticket.
