### ISSUE TITLE
Could not resolve com.redmadrobot:inputmask:4.1.0.

### ISSUE THREAD

**Issue by tdinckaya** [RedMadRobot/input-mask-android#137]
Could not determine the dependencies of task ':app:mergeReleaseNativeLibs'.
> Could not resolve all task dependencies for configuration ':app:releaseRuntimeClasspath'.
   > Could not resolve com.redmadrobot:inputmask:4.1.0.
     Required by:
         project :app > project :react-native-text-input-mask
      > Could not resolve com.redmadrobot:inputmask:4.1.0.
         > Could not get resource 'https://www.jitpack.io/com/redmadrobot/inputmask/4.1.0/inputmask-4.1.0.pom'.
            > Could not GET 'https://www.jitpack.io/com/redmadrobot/inputmask/4.1.0/inputmask-4.1.0.pom'. Received status code 401 from server: Unauthorized

**Comment by osipxd** [comment]
Maven coordinates have been changed after migration from bintray to jitpack.io.
Try `com.redmadrobot:input-mask-android:4.1.0` instead, as it is stated [in the readme](https://github.com/RedMadRobot/input-mask-android?tab=readme-ov-file#gradle).

**Comment by tdinckaya** [comment]
> Maven coordinates have been changed after migration from bintray to jitpack.io. Try `com.redmadrobot:input-mask-android:4.1.0` instead, as it is stated [in the readme](https://github.com/RedMadRobot/input-mask-android?tab=readme-ov-file#gradle).

Thank you sir
