### ISSUE TITLE
Text changes makes the caret jump to the beginning

### ISSUE THREAD

**Issue by gen3ric** [RedMadRobot/input-mask-android#21]
Hi, 

Very new to Android dev and java so I may just be misunderstanding something simple.

I'm using an EditTextPreference declared in XML and then programmatically setting up the input mask, but when adding or deleting text, the caret/cursor jumps to index 0. 

Here's my Java implementation: 
```
EditText editText = ((EditTextPreference) p).getEditText();
MaskedTextChangedListener l = new MaskedTextChangedListener("[_____]{-}[_____]{-}[_____]{-}[_____]{-}[___]", false, editText, null, null);
editText.addTextChangedListener(l);
editText.setOnFocusChangeListener(l);
editText.setHint(l.placeholder());
```

XML declaration:
```
<EditTextPreference
      android:title="License key"
      android:key="license_key"
      android:dialogTitle="License Key"
      android:dialogMessage="Set the location by entering a license key supplied to you. Case insensitive"
      android:defaultValue=""/>
```
Am I missing something?

**Comment by taflanidi** [comment]
Hey @gen3ric 
Thanks for your observation.

Text autocorrection might be a root cause of your problem, as it behaves somewhat weirdly in case when field listener tries to change the text during user input. 

I suggest you to try changing the `inputType` for your text field like this:
```xml
<EditTextPreference
    ...
    android:inputType="textNoSuggestions" />
```
— and let us know, if it helps, as it might be an another limitation we should include into the main README.

**Comment by gen3ric** [comment]
I can confirm that this fixed it. Thanks for the suggestion. I wonder if it is my keyboard? I'm using Google's GBoard on my dev device.

**Comment by taflanidi** [comment]
@gen3ric , good to hear. 

I'm personally using TouchPal third-party keyboard, and it pretty much ignores things like disabling autocorrection, and guys from SwiftKey, for instance, stated that they are going to ignore developer-defined behaviour for autocorrection in response to their user requests.

For God's sake I recommend you to use some workarounds like setting the input type to `textVisiblePassword` for your special text field or else — just try to play with it a little bit more to be sure.

**Comment by gen3ric** [comment]
Sure am - thanks @taflanidi !

**Comment by PingForward** [comment]
I use the SwiftKey an Xiaomi phone and have the same issue.
When I typing caret jumps to the beginning
inputType not helping
```
   <EditText
                android:id="@+id/qwerty"
                android:layout_width="match_parent"
                android:layout_height="54dp"
                android:textSize="23sp"
                android:background="@drawable/edit_text_background"         />
```
Any suggestions?
