### ISSUE TITLE
Optional digits in mask leads to wrong value maskFilled in ValueListener 

### ISSUE THREAD

**Issue by earring** [RedMadRobot/input-mask-android#22]
**Library version:**
2.2.0
**Issue:**
I use optional digits in the end of the input mask, and it leads to wrong value of maskFilled returned by ValueListener attached to MaskedTextChangedListener.
Here's the code:
```java
// EditText carNumber;
carNumberListener = new MaskedTextChangedListener("[00099]", false, carNumber, null, null);
carNumberListener.setValueListener((maskFilled, extractedValue) -> Log.d("mask", "is filled " + maskFilled));
carNumber.addTextChangedListener(carNumberListener);
carNumber.setOnFocusChangeListener(carNumberListener);
```
**Expected result:**
when user entered 3, 4 or 5 digits `maskFilled = true`.

**Actual result:**
when user entered 3 or 4 digits `maskFilled = false`;
when user entered 5 digits `maskFilled = true`.

The same behavior is observed using masks `[09]` and `[A] [000] [AA] [009]`.

**Comment by taflanidi** [comment]
@earring, thanks for your contribution!
Fixed in `2.2.1`, please update your dependencies.
