### ISSUE TITLE
check my string with mask

### ISSUE THREAD

**Issue by Mahdiazadbar** [RedMadRobot/input-mask-android#24]
is there any method for check my string with mask for length and mask of string?

**Comment by taflanidi** [comment]
@Mahdiazadbar I'm not sure what you are talking about. Please, describe your question more specifically or use other words. 

There are several text length-related methods. They expose `Mask` instance [interface](https://github.com/RedMadRobot/input-mask-android/blob/master/inputmask/src/main/kotlin/com/redmadrobot/inputmask/helper/Mask.kt#L183) in [MaskedTextChangedListener](https://github.com/RedMadRobot/input-mask-android/blob/master/inputmask/src/main/kotlin/com/redmadrobot/inputmask/MaskedTextChangedListener.kt#L79) — you may take a look if they could solve your problem.
