### ISSUE TITLE
Optional input characters.

### ISSUE THREAD

**Issue by satorikomeiji** [RedMadRobot/input-mask-android#28]
It would be useful to have the ability to input optional special characters such as '+'. Now it's only letters and numbers.

**Comment by taflanidi** [comment]
Hi @satorikomeiji 
Thanks for your suggestion. I will come back w/ feedback a bit later this week.

**Comment by taflanidi** [comment]
@satorikomeiji and everyone interested: the library with this new feature is going to be updated tomorrow, both for Android and iOS.

**Comment by taflanidi** [comment]
Implemented in `3.3.0`.
