### ISSUE TITLE
Show keyboard if autocomplete = true

### ISSUE THREAD

**Issue by lnfn** [RedMadRobot/input-mask-android#29]
After clicking on the field with autosubstitution not caused by the keyboard. Only after the second click on the field.

**Comment by taflanidi** [comment]
Hey @lnfn may I ask you to provide a part of your project where this issue is reproduced?
I also didn't quite get the statement "not caused by the keyboard". Do you mean you're setting the focus programmatically?

**Comment by lnfn** [comment]
After first clicking on the input field, the keyboard is not displayed

`final MaskedTextChangedListener listener = new MaskedTextChangedListener(
 "{+7} ([000]) [000]-[00]-[00]",
                true,
                editText,
                null,
                valueListener
        );
        editText.addTextChangedListener(listener);
        editText.setOnFocusChangeListener(listener);`
