### ISSUE TITLE
Force field validation after initial value set

### ISSUE THREAD

**Issue by nealsanche** [RedMadRobot/input-mask-android#30]
Is it possible, when initially setting up a `MaskedTextChangedListener` to force the validation and call back the `ValueListener`? I am setting up some EditText fields with the following little method:

```
    private void setupField(EditText editText, String mask, MaskedTextChangedListener.ValueListener valueListener) {
        final MaskedTextChangedListener listener = new MaskedTextChangedListener(
                mask,
                false,
                editText,
                null,
                valueListener
        );

        editText.setOnFocusChangeListener(listener);
        editText.addTextChangedListener(listener);
    }
```

And then in a Fragment's onCreateView I'm setting up some of my fields as follows (I am using databinding):

```
        setupField(binding.viewCreditCardInformation.cardExpirationMonthValue, "[00]", (maskFilled, value) -> {
            expirationMonthFilled = maskFilled;
            updateSubmitButton();
        });

        setupField(binding.viewCreditCardInformation.cardExpirationYearValue, "[0000]", (maskFilled, value) -> {
            expirationYearFilled = maskFilled;
            updateSubmitButton();
        });

        setupField(binding.viewCreditCardInformation.cardSecurityCodeValue, "[000]", (maskFilled, value) -> {
            cvcFilled = maskFilled;
            updateSubmitButton();
        });
```

I find that my value listeners are only getting called on a user typing. Which is fine. I just would also like to trigger these to be called when I set up the current values for the fields when the data is bound to my views. Is that possible?

**Comment by taflanidi** [comment]
Hey @nealsanche!
Thanks for your question.

If I correctly understood you, `MaskedTextChangedListener.setText()` method should help. This method allows to put initial value into the text field, apply formatting and call assigned value listener at the end.
