### ISSUE TITLE
Workaround for android:inputType doesn't work

### ISSUE THREAD

**Issue by trupizzza** [RedMadRobot/input-mask-android#31]
I want to implement masked field as it shown in GIF example with mobile phone number, but also i wan't to show numeric keyboard to input numbers in that field. 
Correct me if I'm wrong - but if i use the code down below:
```java   <EditText
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:id="@+id/phone_masked"
        android:inputType="number"
        android:digits="0123456789 -.+()"
        />

...

            final EditText maskedEditText =  (EditText) getView().findViewById(R.id.phone_masked);
            final MaskedTextChangedListener listener = new MaskedTextChangedListener(
                    "+7 ([000]) [000] [00] [00]",
                    true,
                    maskedEditText,
                    null, null
            );
            maskedEditText.addTextChangedListener(listener);
            maskedEditText.setOnFocusChangeListener(listener);
```
my app crashes and no numeric keyboard appears by tapping on that field.
Is there any way to show numeric keyboard for mobile phone number input, like in GIF example?
https://github.com/RedMadRobot/input-mask-android/raw/assets/assets/gif-animations/direct-input.gif

**Comment by taflanidi** [comment]
Hi @trupizzza!
Thanks for your question. 

First of all, could you please dump your crash log here?

Second, according to your description, there's a strong possibility that the crash isn't caused by the `InputMask`: the library doesn't affect nor override native SDK controls like `EditText`. 

Thus, if no numeric keyboard appears for your input field with `android:inputType="number"` attribute — this means you should double check your source code.

**Comment by trupizzza** [comment]
Thanks for the answer and sorry me for my little Andoid experience.
After making some additional logging, i've got 
"java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first."
That happening because i am trying to init my field as a view in AlertDialog, but define it in activity xml file.
Solve that problem by migrating all properties to method which inits AlertDialog and field.

Now everything working fine! Thanks for that useful project 👍 

btw: maybe it's good to add alternative way how to workaround android:inputType related issue programmatically to readme of a project:
```java
 exditText.setInputType(InputType.TYPE_CLASS_NUMBER);
 exditText.setKeyListener(DigitsKeyListener.getInstance("0123456789 -.+()"));
```

**Comment by taflanidi** [comment]
@trupizzza non-XML approach is a good catch.
I'll add samples for `InputMask vs. android:inputType` and `InputMask vs. autocorrection & prediction` a bit later, thanks.
