### ISSUE TITLE
Wrong formatting when letters mask used [___]

### ISSUE THREAD

**Issue by kvrus** [RedMadRobot/input-mask-android#49]
It works well for digits, but for letters, there is one issue: 
For example mask is [____]
when you type the second character it will turn cursor to the start of the line, so new chars will appear from zero position. 

This is because isDeletion defined in wrong way. I suggest using this method instead
override fun beforeTextChanged(p0: CharSequence?, p1: Int, p2: Int, p3: Int) {
        isDeletion = p2 > p3
        this.listener?.beforeTextChanged(p0, p1, p2, p3)
}

I can't make PR, so will wait for the fix)))

**Comment by taflanidi** [comment]
Hi @kvrus,
Thanks for your report.

You are making a surprisingly big statement there without addressing the root causes.

First of all, what makes you think you understood `isDeletion` correctly?
Second, did you read provided [Known issues](https://github.com/RedMadRobot/input-mask-android#known-issues) section carefully? Especially the [InputMask vs. autocorrection](https://github.com/RedMadRobot/input-mask-android#inputmask-vs-autocorrection--prediction) part.

Now please, kindly set `inputType` of your `EditText` to `textVisiblePassword` and come back with the results, thank you.

**Comment by yatsinar** [comment]
Oh, I had to override this method almost exactly as above. 
I had InputType.TYPE_DATETIME_VARIATION_DATE and custom DigitsKeyListener set up programatically but there was issues with jumping cursor. 
Library code looks like this:

```
    override fun onTextChanged(text: CharSequence, cursorPosition: Int, before: Int, count: Int) {
        val isDeletion: Boolean = before > 0
        //other code
```
Problem is **before** is just the number of replaced characters, but there is also a **count**.
When count is zero - the case is really **isDeletion**. But when **count > 0** and **before > 0** - that's insertion, not deletion. 

Following overriding resolved all the cursor issues:

```
    override fun onTextChanged(text: CharSequence, cursorPosition: Int, before: Int, count: Int) {
        //DO NOT CALL SUPER - this is purposely overwritten onTextChanged implementation
        val isDeletion: Boolean = before > 0 && count == 0
        //other code is the same as in library
```
That was quite ad hoc solution, but you definitely could look into that line closer and probably will be able to resolve one of "Known issues".

**Comment by taflanidi** [comment]
Hi @yatsinar!
Thanks for your comment.

> Oh, I had to override this method almost exactly as above.

To be honest, your solution sounds almost nothing like the proposal above.
Moreover, it resembles the logic used in our [iOS library counterpart ](https://github.com/RedMadRobot/input-mask-ios/blob/master/Source/InputMask/InputMask/Classes/View/MaskedTextFieldDelegate.swift#L303), verbatim. 

Which makes it a perfect candidate for a pull request.
Would you like to submit your fix to our library?

**Comment by yatsinar** [comment]
Yeah, sure, replacement)

**Comment by taflanidi** [comment]
@yatsinar, `2.3.1` has been published.
Thanks for your contribution!
