### ISSUE TITLE
Editing is broken

### ISSUE THREAD

**Issue by alaershov** [RedMadRobot/input-mask-android#5]
I used the watcher from the sample, and the editing does some strange things.

Enter some valid phone number, e.g. +7 (923) 123 45 67

For instance, I made a mistake in "45", and want to change it to "78"

I place cursor after "45": 
`+7 (923) 123 45<cursor> 67`

I press backspace, and expect to get this:
`"+7 (923) 123 4<cursor>6 7"`
but suddenly get this:
`"+7 (923) 123 <cursor>46 7"`

This is definitely not what I wanted, please fix it or explain how to set up the watcher to support editing correctly, maybe it's my mistake somehow :)

**Comment by taflanidi** [comment]
Hey, @alaershov 
Please, double check and make sure you are using the latest version of the library.

We've fixed this bloomer in `1.0.1`, and it definitely reproduces for the `1.0.0` version, so I guess you might be using an outdated code.

**Comment by alaershov** [comment]
Indeed, 1.0.1 fixes it. You should update your installation guide then, it's 1.0.0 there.

**Comment by taflanidi** [comment]
Done.
