### ISSUE TITLE
Format Money

### ISSUE THREAD

**Issue by oreis91** [RedMadRobot/input-mask-android#52]
Hello, does this feature have a cash/price format? reverse the digits when typing

**Comment by taflanidi** [comment]
Hi @oreis91!
Thanks for your question. I'm not sure I got it right, though. 

Right now I'm working on a feature request from this issue report [here](https://github.com/RedMadRobot/input-mask-ios/issues/25). It's the iOS library counterpart. Both Android and iOS versions usually receive the same features, thus you'll see right text alignment implemented for input-mask-android, too.

Is this the feature you are looking for?

**Comment by oreis91** [comment]
Example: 123.456.78 (left to right)
To: 12.345.678

**Comment by oreis91** [comment]
Example: https://i.stack.imgur.com/p5lzs.gif

**Comment by PriscyllaT** [comment]
hi, @oreis91 Did you solve it?

**Comment by oreis91** [comment]
@PriscyllaT tem skype?

**Comment by PriscyllaT** [comment]
@oreis91 email: priscyllaforwork@gmail.com

**Comment by oreis91** [comment]
@taflanidi thank's

**Comment by taflanidi** [comment]
@oreis91, @PriscyllaT,
I've added `Custom notations` with the latest update; it's a major patch and a main step towards money formatting like you described.

Next update is scheduled for tomorrow, and you'll have your feature added.

**Comment by oreis91** [comment]
final List<String> affineFormats = new ArrayList<>();
        affineFormats.add("8 ([000]) [000] [000] [00]");

        final MaskedTextChangedListener listener = new PolyMaskTextChangedListener(
            "+7 ([000]) [000] [00] [00]",
            affineFormats,
            true,
            editText,
            null,
            new MaskedTextChangedListener.ValueListener() {
                @Override
                public void onTextChanged(boolean maskFilled, @NonNull final String extractedValue) {
                    Log.d(MainActivity.class.getSimpleName(), extractedValue);
                    Log.d(MainActivity.class.getSimpleName(), String.valueOf(maskFilled));
                }
            }
        );



not work, error code

**Comment by oreis91** [comment]
## I can not adapt to the new version help me?

**Comment by taflanidi** [comment]
@oreis91 oh, wow, now that's a bummer.

I forgot to add convenience constructors for the sake of backward compatibility.
Nevertheless, meet `ReversedMaskTextChangedListener` in `3.4.0`.

This new listener works as follows:

1. Instantiate instance as usually:

```java
final MaskedTextChangedListener reversedListener = new ReversedMaskTextChangedListener(
    "[000] [000] [000] [000] [000]",
    editText,
    new MaskedTextChangedListener.ValueListener() {
        @Override
        public void onTextChanged(boolean maskFilled, @NonNull final String extractedValue) {
            Log.d(MainActivity.class.getSimpleName(), extractedValue);
            Log.d(MainActivity.class.getSimpleName(), String.valueOf(maskFilled));
        }
    }
);
```
2. Register newly instantiated listener:
```java
editText.addTextChangedListener(reversedListener);
editText.setOnFocusChangeListener(reversedListener);

editText.setHint(reversedListener.placeholder());
```
3. Make sure your text field annotated correctly:
```xml
<EditText
    android:id="@+id/edit_text"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:digits="1234567890 "
    android:gravity="end"
    android:inputType="number"
    android:textAlignment="textEnd" />
```

— later on, I'll add this information to the main README.

P.s. Unfortunately, you won't be able to use decimal format. I'll need some time to investigate that.

**Comment by oreis91** [comment]
Android Studio does not compile a latest version 3.4.0

`Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.redmadrobot:inputmask:3.4.0`

**Comment by oreis91** [comment]
```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: br.com.bcarros, PID: 31549
                  java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;
                      at com.redmadrobot.inputmask.ReversedMaskTextChangedListener.<init>(ReversedMaskTextChangedListener.kt)
                      at br.com.bcarros.apk.InstitutionalFinanceActivity.onCreate(InstitutionalFinanceActivity.java:173)
                      at android.app.Activity.performCreate(Activity.java:6955)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3045)
                      at android.app.ActivityThread.-wrap14(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6776)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
```

**Comment by SergeyTrukhachev** [comment]
Unfortunately, ReversedMaskTextChangedListener doesn't work for me. 
I use the following mask `[9],[999],[999]`, but whenever I enter a value (for example 1234567), I get the following sequence:
1
12
123
1,234
1,2,345
2,3,456
3,4,567
and If I keep entering more numbers it behaves in the same way:
4,5,678
5,6,789

Is it expected behavior?

**Comment by Madina-S** [comment]
Is there any news about ReversedMaskTextChangedListener?

**Comment by taflanidi** [comment]
Hey everyone.
We've introduced some major updates, including an [RTL](https://github.com/RedMadRobot/input-mask-android/wiki/2.2-Right-to-Left-&-Digit-Grouping) functionality.

Please, give it a try!

P.s. Should you have any issues, please do not hesitate to open **new** tickets instead of commenting on the closed ones.
