### ISSUE TITLE
Не работает форматирование телефона

### ISSUE THREAD

**Issue by igorkazakov** [RedMadRobot/input-mask-android#53]
исходные данные: 
```
<EditText
            android:id="@+id/editTextPhone"
            style="@style/CabinetEditTextStyle"
            android:layout_height="40dp"
            android:layout_marginLeft="@dimen/registration_side_margin"
            android:layout_marginRight="@dimen/registration_side_margin"
            android:layout_marginTop="@dimen/registration_input_top_margin"
            android:hint="@string/registration_phone"
            android:inputType="phone"
             />
```

```
final MaskedTextChangedListener listener = new MaskedTextChangedListener(
                "+7 ([000]) [000]-[00]-[00]",
                true,
                mEditTextPhone,
                null,
                (maskFilled, extractedValue) -> {
                    String phone = mEditTextPhone.getText().toString();
                    getPresenter().onPhoneChangeText(phone);
                }
        );

        mEditTextPhone.addTextChangedListener(listener);
        mEditTextPhone.setOnFocusChangeListener(listener);
        mEditTextPhone.setHint("+7 (___) ___-__-__");
```

Ввожу цифру 6, получается +7 (6, затем перевожу курсор на цифру 7 и ввожу 4, то получится +7 (476, автоматически ввелась лишняя цифра 7!!! Баг проявится с любыми числами, важна лишь последовательность

**Comment by taflanidi** [comment]
Привет @igorkazakov!
Спасибо за сообщение.

С моей стороны поведение воспроизводится в том случае, когда курсор стоит **перед** семёркой, а не после. Если это соответствует описанной вами ситуации, тогда происходит следующее (чертой отмечено положение каретки).
```
+|7 (6
```
Цифра 4 вставляется перед семёркой:
```
+4|7 (6
```
После происходит форматирование текста, и цифры `476` переезжают вперёд:
```
+7 (4|76
```
— и это не дефект, а ожидаемое поведение. То же самое произойдёт, если в пустое поле ввести «+»
```
+
```
а потом из буфера обмена вставить номер без кода страны: `962 123-45-67`:
```
+7 (962) 123 45 67
```

**Comment by taflanidi** [comment]
@igorkazakov, так не пойдёт.

> не избавляет от случайной ошибки

Ваш аргумент — подмена тезиса. Нет никаких сомнений в том, что ошибки пользовательского ввода нужно сводить к минимуму. В идеале — на глазах у самого пользователя.

Но никто в здравом уме не станет писать и вставлять в мобильное приложение нейронную сеть, которая смогла бы отслеживать и корректировать все ошибки ввода _ради номера телефона_.

И да простят меня коллеги из Сбертеха, но их решение стирать **весь** номер при малейшей оплошности — это решение на «отстань», в котором больше вреда, чем стремления помочь пользователю. Куда логичнее выглядел бы отказ от форматирования вообще, и текстовое поле с одиннадцатью цифрами `71234567890`.

> минимизирующее ошибку

О каких ошибках идёт речь? Я, например, говорю об ошибке формата данных, которой не возникнет, если библиотека используется правильно и по назначению. Телефон всегда будет в формате `+7 (000) 000 00 00`, поставленная задача — решена. Ваша претензия состоит конкретно в чём?

*** 

Вот ещё пару камней на чашу весов. Пользователь попадает на экран ввода номера, текстовое поле активно и отображает `+7 (`, курсор в конце, клавиатура поднята. Какое событие более вероятно? 

1. Пользователь продолжит вводить номер телефона
2. Пользователь поставит курсор между символами «+» и «7» и продолжит вводить номер телефона

Не нужно быть гением UX, чтобы выбрать п.1, но предположим, что пользователю действительно потребовалось исправить номер страны, или он просто хочет ввести «8» вместо «+7».

Что обычно делает человек, когда при наборе слова обнаруживает опечатку в первой букве? Ответ: он стирает слово целиком, нажимая несколько раз `Backspace` или один раз `^Backspace` (`⌥Backspace` для macOS). 

Исправлять «+7» пользователь будет через удаление всей строки `+7 (`, и этот сценарий отрабатывается через `PolyMaskTextChangedListener` и аффинный формат `8 (000) 000 00 00`.

Далее, если из строки «`+`7` (`962`) `123» удалить форматирование, то получится «7962123», то есть цифры, которые действительно важно получить от пользователя. Конечная цель функции — получить именно эти цифры.

Что будет, если в «7962123» пользователь вставит «4»? 

7962**4**123

Если вернуть форматирование, цифры «123» сдвинутся вправо:

`+`7` (`962`) `412` `3

— это типичное поведение любого текстового поля. Когда в строку вставляется символ, конец строки не удаляется, не переписывается, а сдвигается вправо. Но что будет, если к «7962123» дописать «4» в самом начале?

**4**7962123

Номер телефона в РФ _не может начинаться с четвёрки_. Значит, на первое место нужно вставить цифру 7:

747962123

Если вернуть форматирование, то получится:

`+`7` (`479`) `621` `23

Альтернативный пример: пользователь вставляет из буфера обмена московский номер «4951234567». Номер телефона в РФ _не может начинаться с четвёрки_, поэтому на первое место нужно вставить цифру 7:

74951234567

Если вернуть форматирование, то получится:

`+`7` (`495`) `123` `45` `67

Библиотека никак не отслеживает, куда вставляются символы, где нажимается `Backspace`, где был использован буфер обмена. Всё это потребовало бы колоссальных объёмов логики, если учесть, что библиотека поддерживает не только номера телефонов, но и вообще любой вид значений с фиксированным форматом (а с недавних пор и строки бесконечной длины).

Библиотека форматирует конечное значение. Если на вход подаётся строка «479621230567», библиотеке неизвестно, была ли цифра 4 вставлена в «79621230567», или же вся строка была вставлена из буфера обмена, или же в «879621230567» была удалена цифра 8. Отсюда получается конечное поведение.

***

В любом случае, библиотечные классы-слушатели открыты для наследования, и заточить поведение для конкретного частного случая никто не запрещает.
