### ISSUE TITLE
Adjust gradle including documentation to latest version of the dependency: 3.4.0

### ISSUE THREAD

**Issue by SeppPenner** [RedMadRobot/input-mask-android#54]
The documentation states to add this to your gradle file:

```gradle
repositories {
    jcenter()
}

dependencies {
    implementation 'com.redmadrobot:inputmask:3.3.0'
}
```
See https://github.com/RedMadRobot/input-mask-android#gradle

However, the latest version is 3.4.0, https://github.com/RedMadRobot/input-mask-android/releases/tag/3.4.0.

This should be updated. See my pull request, too: https://github.com/RedMadRobot/input-mask-android/pull/55

**Comment by taflanidi** [comment]
Mr. @SeppPenner, pull request accepted.
We've got our hands full, and you are the best.
