### ISSUE TITLE
Replacing last symbol works weird

### ISSUE THREAD

**Issue by alaershov** [RedMadRobot/input-mask-android#6]
Using sample code from the guide:
Enter:
`+7 (123) 456 78 90`

Then place cursor here:
`+7 (<cursor>123) 456 78 90`

Start entering something else (for instance, all aeros):
`+7 (000) 000 00 0<cursor>1`

If I press "0" one more time, I get this:
`+7 (000) 000 00 0<cursor>0`
instead of this (which is expected):
`+7 (000) 000 00 00<cursor>`

**Comment by taflanidi** [comment]
@alaershov, looks like both [iOS](https://github.com/RedMadRobot/input-mask-ios) and Android versions of the library had this issue. 

Fixed in `1.0.2`
