### ISSUE TITLE
ReversedMaskTextChangedListener allows endless input

### ISSUE THREAD

**Issue by MRezaNasirloo** [RedMadRobot/input-mask-android#61]
Hi, Nice project

`ReversedMaskTextChangedListener` allows endless input, It means any entered number will erase the first entered numbers, I think the expected behavior is the behavior I get with the `PolyMaskTextChangedListener` and `MaskedTextChangedListener` which does not let the user enter more numbers than the size provided in the mask

```java
final MaskedTextChangedListener listener = new ReversedMaskTextChangedListener(
                "[000],[000],[000]",
                editText,
                new MaskedTextChangedListener.ValueListener() {
                    @Override
                    public void onTextChanged(boolean maskFilled, @NonNull final String extractedValue) {
                        Log.d(MainActivity.class.getSimpleName(), extractedValue);
                        Log.d(MainActivity.class.getSimpleName(), String.valueOf(maskFilled));
                    }
                }
        );
```

**Comment by taflanidi** [comment]
Hey @MRezaNasirloo!
Thanks for your report.

I'll need some more time to look into it. I'm going to revert to this issue in a day or two, thanks for your patience!

**Comment by taflanidi** [comment]
@MRezaNasirloo, since our library turned v.4, we end up support for the `ReversedMaskTextChangedListener` class.

Please, refer to our current changelog for details. A more reliable implementation is coming soon.
