### ISSUE TITLE
Format Money Thousand Separator

### ISSUE THREAD

**Issue by SyntaxError001** [RedMadRobot/input-mask-android#62]
Hi, good day! I have an inquiry about the formatter for Text Mask Input. All of the mask are working aside from the Money Format.  I can't find a way to format money input. I want something to look like this:

1
12
123
1,234
12,345
123,456
1,234,567
12,345,678
123,456,789

Can you help me out about this issue? Please see attached picture below. Thank you so much in advance!

![screen shot 2018-09-25 at 2 15 08 pm](https://user-images.githubusercontent.com/43564319/45996100-7f37eb80-c0cd-11e8-9905-238f8a12b5c6.png)

**Comment by taflanidi** [comment]
Hey @SyntaxError001!
Thanks for your question.

As a temporary solution you may try to use our `ReversedMaskTextChangedListener` with a `[000] [000] [000]` mask — though, the class is highly unstable. I didn't even mention it in the main README.

I know this is an extremely popular scenario, so I'm working on a solution to cover this case, too.
My plans include issuing an update this week, so please stay tuned.

**Comment by SyntaxError001** [comment]
Thank you so much @taflanidi!

Will wait for the update. 👍

**Comment by MRezaNasirloo** [comment]
Any Update on this?

**Comment by patrickpilch** [comment]
@taflanidi
Any other features we could look into to implement this functionality?

**Comment by gsbarbosa** [comment]
I need this solution too. Any update?

**Comment by taflanidi** [comment]
Please consider reading about [RTL masks](https://github.com/RedMadRobot/input-mask-android/wiki/2.2-Right-to-Left-&-Digit-Grouping).

Also keep an eye on our changelog. While the work is still in progress — we haven't figured out digit grouping for decimal sums of money yet — the solution is already close.

In theory, the essential part for this functionality to work properly is a special affinity calculation strategy allowing to effectively switch between these two formats in RTL mode:

```
[000] [000] [000] EUR
[000] [000] [000]{,}[00] EUR
```

**Comment by taflanidi** [comment]
Done.
