### ISSUE TITLE
У кого не до конца стирается текст при помощи Backspace

### ISSUE THREAD

**Issue by CoolMind** [RedMadRobot/input-mask-android#64]
Спасибо за библиотеку!
Если вы создаёте listener в `onCreateView()` (`onCreate()`), а добавляете его в `onResume()` и удаляете в `onPause()`, возможна следующая трудность.

   onCreateView():

        listener = new MaskedTextChangedListener("+[0] ([000]) [000]-[0000]", phone, null);

onResume():

        super.onResume()
        phone.addTextChangedListener(listener);
        phone.onFocusChangeListener = listener;

onPause():

        phone.removeTextChangedListener(listener);
        phone.onFocusChangeListener = null;
        super.onPause();

Если вы будете набирать и удалять текст Backspace'ом, то в некоторых случаях он удаляется не до начала, а до первого нецифрового символа (дефис, скобка). Тогда следует проверить, что `onResume()` не вызывается два раза подряд (или случайно не сделали где-то раньше `phone.addTextChangedListener(listener);`. Такое возможно, если в активности вы принудительно вызываете `onResume()` верхнего фрагмента.

**Comment by taflanidi** [comment]
Привет @CoolMind!
Спасибо за отзыв.

Я благодарен за предупреждение возможной проблемы, однако описанная ситуация вызывает слишком много вопросов у меня и у моих коллег.

А вот эта фраза меня даже слегка пугает:

> Такое возможно, если в активности вы принудительно вызываете onResume() верхнего фрагмента.

Это прямое нарушение инкапсуляции. _Что может пойти не так?_ ©

С какой целью вы «размазываете» настройку текстового поля по жизненному циклу? Что это даёт?

Метод `addTextChangedListener()` не идемпотентный, его нельзя просто так вызывать в `onResume()`. Почему вы предварительно не чистите список слушателей через `removeTextChangedListener()` прямо перед `addTextChangedListener()`, если всё-таки необходимо добавлять слушателя именно в `onResume()`?

**Comment by CoolMind** [comment]
Добрый день, @taflanidi!

> Это прямое нарушение инкапсуляции. Что может пойти не так? ©

Не вижу здесь нарушения инкапсуляции, поскольку активности и фрагменты наследуются от разных классов. Мне необходимо, чтобы вызывался метод `onResume()` фрагмента, но это происходит не всегда. В этом случае я могу прописать вызов `onResume()` принудительно из активности.

> С какой целью вы «размазываете» настройку текстового поля по жизненному циклу? Что это даёт?

Это стандартный в Андроиде подход, когда обработчики событий подписываются, отписываются в `onResume()`, `onPause()`, чтобы не реагировать на события в остальное время. Примером можно назвать добавление фрагментов во фрагмент-менеджер через `add()`, а не `replace()`, когда оба фрагмента становятся видимыми.

> Метод addTextChangedListener() не идемпотентный, его нельзя просто так вызывать в onResume(). Почему вы предварительно не чистите список слушателей через removeTextChangedListener() прямо перед addTextChangedListener(), если всё-таки необходимо добавлять слушателя именно в onResume()?

Потому что я чищу список слушателей в `onPause()`, и этого обычно достаточно. Если бы я чистил в `onResume()`, то предполагалось, что они подключены и существуют, а кроме того, я и не думал, что их там может оказаться два-три-десять одинаковых.

**Comment by taflanidi** [comment]
Очень плохо, @CoolMind.
Вместо того, чтобы разобрать ситуацию и признать свой косяк, вы уходите в отрицание и начинаете придумывать оправдания своей ерунде.

> Не вижу здесь нарушения инкапсуляции, поскольку активности и фрагменты наследуются от разных классов.

Что за чушь? Я вообще ничего не писал про `Activity`.

Нельзя просто так брать — и дёргать системные методы у фрагмента просто потому что он не `Activity`. Что это за аргумент?

Этот метод _вам не принадлежит_. Вы думаете, в нём просто так должен вызываться `super`?

Более того скажу, Android SDK тут вообще ни при чём. `Activity` или `Fragment` — не имеет значения. У ряда шаблонов проектирования ([Factory method](https://en.wikipedia.org/wiki/Factory_method_pattern), [Chain of responsibility](https://en.wikipedia.org/wiki/Chain-of-responsibility_pattern), [Command](https://en.wikipedia.org/wiki/Command_pattern), [Template method](https://en.wikipedia.org/wiki/Template_method_pattern) и другие) есть методы, которые точно так же _вам не принадлежат_, они лежат в другом слое абстрации, и их нельзя от балды напрямую вызывать.

И да, `Fragment lifecycle` — это прямая реализация шаблона `Template method`. 

Можно было банально сделать так:

```java
void onResume() {
    super.onResume();
    configureTextFields();
}

void configureTextFields() {
   // я могу вызывать этот метод вообще в любой момент
}
```

Вместо этого вы безо всяких причин нарушаете инкапсуляцию, нарушаете [LSP](https://en.wikipedia.org/wiki/Liskov_substitution_principle) и [OCP](https://en.wikipedia.org/wiki/Open–closed_principle), и осложняете жизнь себе и своим коллегам по проекту. Если не сейчас, то в будущем.

> Это стандартный в Андроиде подход

... который вы притянули за уши вместо того, чтобы ответить на мой прямой вопрос:

> Что это даёт?

_Вам_. Что это даёт _вам_, вашему проекту? Какую выгоду вы получаете от того, что (_опять!_) усложняете жизнь себе и своим коллегам? «Best practices», «Это стандартный подход»... бросать пыль в глаза вместо того, чтобы ответить по существу — какую вы ожидали реакцию от меня?

Я открыто утверждаю: вы вставили палку в колесо своего велосипеда на полном ходу, и теперь героически превозмогаете трудности, которые сами себе создали.

> Если бы я чистил в onResume(), то предполагалось, что они подключены и существуют, а кроме того, я и не думал, что их там может оказаться два-три-десять одинаковых.

А вы документацию читаете перед тем, как использовать инструмент?

![image](https://user-images.githubusercontent.com/6849363/47915506-c32bc680-deab-11e8-862a-a76cae84f5fa.png)

`List`. Знаете, `ArrayList`, `LinkedList`, вот эти ребята. Не `Set`.

Да даже в документацию лазить не нужно. Метод называется ` ADD TextChangedListener`. У вас состояние фрагмента восстанавливается после _паузы_. С чего вдруг список слушателей должен был стать пустым?

***

Самое забавное, что ваш изначальный посыл был помочь людям избежать возможной ошибки, но вы не удосужились даже перевести первое сообщение на английский язык.

Итого:

0. Вам следует пройти курс объектно-ориентированного дизайна. Любой, вам нужно усвоить основы.
1. Прочтите «Чистый код» и прочие книжки дяди Боба, Мартина Фаулера и др., которые сможете найти. Ключевые слова: `SOLID`, `OOD`. Перечитайте ещё раз, если уже читали.
2. _Переделайте_ свой проект, сделайте его проще и чище.
