### ISSUE TITLE
Поддержка RTL

### ISSUE THREAD

**Issue by epifanov-konstantin** [RedMadRobot/input-mask-android#66]
Здравствуйте!
При реализации в приложении персидской локализации (Right To Left) возникла проблема с отображением маски в EditText. Маска отзеркалилась, но не верно:

в обычном макете (Left To Right) маска +7 ([000]) [000]-[00]-[00]
при заполнении ведёт себя так: +7 (123) 456-78-90. (слева направо, как и ожидается)
в макете Right To Left так: 456-78-90 (123) 7+, то есть сама строка заполняется справа налево, но внутри блоков - слева направо.

другой пример, маска карты - [0000] [0000] [0000] [0000]
LTR - 1234 5678 9099 9999
RTL - 9999 9099 5678 1234

Пытался отключить RTL для поля, добавив android:layoutDirection="ltr" - но это не дало результатов, поле по прежнему заполняется справа налево и в неправильном порядке.

Подскажите, пожалуйста, как сделать так, что бы при работе приложения в RTL режиме, поля с масками продолжали работать в LTR режиме ?

P.S.: Спасибо большое за вашу работу, библиотека отличная!

**Comment by taflanidi** [comment]
@epifanov-konstantin, доброго времени суток!
Спасибо за извещение, случаев с RTL у нас ещё не было.

Мне понадобится дополнительное время разобраться, в чём дефект. ETA ~ суббота-воскресенье.

Вы не могли бы уточнить, имеет ли эффект установка `layoutDirection="ltr"` у элемента `Layout`, в котором находится текстовое поле?

N.B. У нас есть нестабильный класс `ReversedMaskTextChangedListener`, предназначенный для условий ввода данных с правым выравниванием (например, количество денег `$1 000 000`). Можете попробовать поэкспериментировать ещё и с ним.

**Comment by epifanov-konstantin** [comment]
@taflanidi, пробовал выставить `layoutDirection="ltr"` родительскому `Layout` - без изменений.

По поводу `ReversedMaskTextChangedListener` - там перезаписываются символы, при вводе большего количества знаков, чем допускает маска, при этом в режиме RTL невозможно удалить знак, и запись идёт слева направо, а маска при этом отзеркалена, в общем это еще сложнее)

**Comment by taflanidi** [comment]
@epifanov-konstantin, сейчас работаю над решением вашей проблемы.

Восток — дело тонкое, персидская локаль, по ходу, тоже не сахар...

**Comment by epifanov-konstantin** [comment]
@taflanidi, отлично, спасибо большое!
