### ISSUE TITLE
Dynamic mask is possible?

### ISSUE THREAD

**Issue by RodrigoNovais** [RedMadRobot/input-mask-android#68]
Is it possible to dynamically change the mask?
I'm using MaskedTextChangedListener and SwitchCompat  to change the pattern of documents in a view but it's not switching and I'm getting this error
java.lang.IndexOutOfBoundsException: setSpan (3 ... 3) ends beyond length 2

![image](https://user-images.githubusercontent.com/11841314/48005473-ae913d80-e0fa-11e8-9da6-9ece939ce2f5.png)

**Comment by taflanidi** [comment]
Hey @RodrigoNovais!
Thanks for your report.

I'm afraid I'll need a little bit more detail from you about your situation. For instance, you've got two methods returning a `TextWatcher` (`cnpjListener()` and `cpfListener()`). Are these actually "getters", meaning they return the same object each time you call them?

I mean, I'm not sure you won't get two different listeners in these two lines:
```java
documentView.addTextChangedListener(cpfListener()); 
documentView.setOnFocusChangeListener(cpfListener());
```

Now, in order to solve your problem, my first suggestion would be for you to clear the `documentView.text` just **after** you change the pattern of document. You should also consider using the `listener.setText("")` method instead of assigning the empty string directly.

Please, let me know the results. I've made a sample code for you below.

```java
MaskedTextChangedListener cpf = cpfListener();
MaskedTextChangedListener cnpj = cnpjListener();
documentView.removeTextChangedListener(cnpj);
documentView.removeTextChangedListener(cpf);

if (isChecked) {
    documentView.addTextChangedListener(cpf); 
    documentView.setOnFocusChangeListener(cpf);
    cpf.setText("");
} else {
    documentView.addTextChangedListener(cnpj); 
    documentView.setOnFocusChangeListener(cnpj);
    cnpj.setText("");
}

**Comment by RodrigoNovais** [comment]
I'm sorry for leave this questions, I didn't realize I posted my code incomplete
I've tried the way you said but I getting another error now

java.lang.NullPointerException: Attempt to invoke virtual method 'void com.redmadrobot.inputmask.MaskedTextChangedListener.setText(java.lang.String)' on a null object reference

That is my code

```
MaskedTextChangedListener cpf;
MaskedTextChangedListener cnpj;

private EditText documentView;
private SwitchCompat switchView;
```
```
switchView = root.findViewById(R.id.switch_customer);
documentView = root.findViewById(R.id.customer_document);
switchBetweenMasks(switchView.isChecked());
switchView.setOnCheckedChangeListener(new CompoundButton.OnCheckedChangeListener() {
    @Override
    public void onCheckedChanged(CompoundButton buttonView, boolean isChecked) {
        switchBetweenMasks(isChecked);
    }
});

documentView.setOnEditorActionListener(new TextView.OnEditorActionListener() {
    @Override
    public boolean onEditorAction(TextView textView, int id, KeyEvent event) {
        if (id == EditorInfo.IME_ACTION_NEXT && documentValidator()) {
            clearError();
            streetView.requestFocus();
            return true;
        }
        return false;
    }
});

cpf = cpfListener();
cnpj = cnpjListener();
```
```
private void switchBetweenMasks(boolean isChecked) {
    Log.e("switchBetweenMasks: ", String.valueOf(isChecked));
    documentView.removeTextChangedListener(cnpj);
    documentView.removeTextChangedListener(cpf);
     if (isChecked) {
        documentView.addTextChangedListener(cnpj);
        documentView.setOnFocusChangeListener(cnpj);
        cnpj.setText("");
    } else {
        documentView.addTextChangedListener(cpf);
        documentView.setOnFocusChangeListener(cpf);
        cpf.setText("");
    }
}
```
```
private MaskedTextChangedListener cpfListener() {
    return new MaskedTextChangedListener("[000].[000].[000]-[00]", documentView, null);
}

private MaskedTextChangedListener cnpjListener() {
    return new MaskedTextChangedListener("[00].[000].[000]/[0000]-[00]", documentView, null);
}
```

**Comment by RodrigoNovais** [comment]
It worked well based on your sample, thank you
