### ISSUE TITLE
maskFilled wrong value for subsequent optional blocks

### ISSUE THREAD

**Issue by peanutwolf** [RedMadRobot/input-mask-android#70]
**Library version:**
4.0.0
**Issue:**
Hello,
I've faced the issue of wrong 'maskFilled' argument value when subsequent blocks with optional digits had been installed.

Consider the following example:
```
MaskedTextChangedListener.installOn(
    testEditText,
    "[0000] [9999] [999]",
    object : MaskedTextChangedListener.ValueListener{
        override fun onTextChanged(maskFilled: Boolean, extractedValue: String) {
            Log.d("TEXT_CHANGED", "extractedValue=[$extractedValue], maskFilled=[$maskFilled]")
        }
    }
)
```
The actual output as follows:
```
D/TEXT_CHANGED: extractedValue=[111], maskFilled=[false]  
D/TEXT_CHANGED: extractedValue=[1111], maskFilled=[false] 
D/TEXT_CHANGED: extractedValue=[11111], maskFilled=[false]
D/TEXT_CHANGED: extractedValue=[111111], maskFilled=[false]
D/TEXT_CHANGED: extractedValue=[1111111], maskFilled=[false]
D/TEXT_CHANGED: extractedValue=[11111111], maskFilled=[true]
D/TEXT_CHANGED: extractedValue=[111111111], maskFilled=[true]
```

But the expected output should be:
```
D/TEXT_CHANGED: extractedValue=[111], maskFilled=[false]  
D/TEXT_CHANGED: extractedValue=[1111], maskFilled=[true] 
D/TEXT_CHANGED: extractedValue=[11111], maskFilled=[true]
D/TEXT_CHANGED: extractedValue=[111111], maskFilled=[true]
D/TEXT_CHANGED: extractedValue=[1111111], maskFilled=[true]
D/TEXT_CHANGED: extractedValue=[11111111], maskFilled=[true]
D/TEXT_CHANGED: extractedValue=[111111111], maskFilled=[true]
```

Thanks in advance.

**Comment by taflanidi** [comment]
@peanutwolf,
Meanwhile, I'd like to suggest you an [Affine masks](https://github.com/RedMadRobot/input-mask-android#affine-masks) approach. This could be an addition to the value validation in your project.

The `installOn` method returns an `MaskedTextChangedListener` with its `affineFormats` property.

Having `[0000]` as a primary format with two additional
```
[0000] [0000]
[0000] [0000] [000]
```
affine formats will ensure your `value` is exactly `4` or `8` or `11` digits long when the `maskFilled` is true.

**Comment by peanutwolf** [comment]
@taflanidi,
Thanks for the suggestion.

My final goal is to handle [Primary Account Number](https://en.wikipedia.org/wiki/Payment_card_number#Issuer_identification_number_(IIN)) entry. 

It happens to be that PAN can be from 12 to 19 digits.
In the starter post I've provided the shortened version of mask for simplicity.

So in order to achieve that presumably my affine formats list should look like:
```
val affineFormats = listOf(
    "[0000] [0000] [0000] [0999]",
    "[0000] [0000] [0000] [0099]",
    ...
    "[0000] [0000] [0000] [0000] [009]",
    "[0000] [0000] [0000] [0000] [000]"
)
````
Guess I'll find out how to handle it for now. Not a big deal.
Anyway will be waiting for an update.

**Comment by taflanidi** [comment]
Hey @peanutwolf!
I'm sorry for the delay.

It seems like it's safe to apply this new patch we discussed above, both for Android and iOS versions.
The library is going to receive an update soon, so please stay tuned.

**Comment by taflanidi** [comment]
Resolved in `4.1.0`

**Comment by peanutwolf** [comment]
Good news. Thanks a lot.

**Comment by taflanidi** [comment]
@peanutwolf, well, it took a while. I'm sorry about that.
