### ISSUE TITLE
Affinity masks with a default (For a credit card)

### ISSUE THREAD

**Issue by Zeliret** [RedMadRobot/input-mask-android#72]
Hi guys! Such a brilliant library you have!

I have a small question. Here is a piece of code:
```kotlin
MaskedTextChangedListener.installOn(
            binding.paymentCardNumberLayout.editText!!,
            "[0000] [0000] [0000] [0000] [999]",
            affineFormats = listOf(
                "3[000] [000000] [00009]",              // American Express, Diners Club (14-15)
                "4[000] [0000] [0000] [0000] [999]",    // Visa (16-19)
                "5[000] [0000] [0000] [0000] [999]",    // Master Card (16-19)
                "6[000] [0000] [0000] [0000]"           // Discover (16)
            ),
            affinityCalculationStrategy = AffinityCalculationStrategy.PREFIX)
``` 
I want my user to start typing his card number and if it starts with one of the affinity prefixes so use it to format. But in this example the default mask is always used.

If I change the default mask to "4[000] [0000] [0000] [0000] [999]" for example it works like a charm. But there is always "4" in the edittext on the first display of the form.

**Comment by Zeliret** [comment]
@taflanidi Thanks for the quick reply!
Nullifying the focus listener did a trick but there is another problem. When I start input a digit in an empty field and it is not present in any masks I get "4<my digit>...". It is like "4" prepends automatically on first input char. 

Is it possible to achieve such a behavior when I can define some prefixes (3, 4, 5, 6, etc.) and switch masks on the fly but fallback to some general mask if I start typing for example with 9?

**Comment by taflanidi** [comment]
@Zeliret, the rule of thumb is to have the most generic mask as the last affine format.

**Comment by Zeliret** [comment]
@taflanidi Wow, it seems that this code works like I wanted. But I needed to order the affinity items by length asc. 
```kotlin
MaskedTextChangedListener.installOn(
            binding.paymentCardNumberLayout.editText!!,
            "",
            affineFormats = listOf(
                "3[000] [000000] [00009]",              // American Express, Diners Club (14-15)
                "6[000] [0000] [0000] [0000]",          // Discover (16)
                "[0000] [0000] [0000] [0000] [999]"     // Visa (16-19), Master Card (16-19)
            ),
            affinityCalculationStrategy = AffinityCalculationStrategy.WHOLE_STRING,
            valueListener = object : MaskedTextChangedListener.ValueListener {
                override fun onTextChanged(maskFilled: Boolean, extractedValue: String) {
                    vm.cardNumber.setUnmasked(extractedValue)
                }
            })
```

**Comment by taflanidi** [comment]
Hey @Zeliret!
Could you please confirm your problem is solved, and close this issue?

**Comment by Zeliret** [comment]
Yeah, thank you!
