### ISSUE TITLE
How to use input-mask-android with TextInputEditText material art ?

### ISSUE THREAD

**Issue by omidraha** [RedMadRobot/input-mask-android#76]
Hi,
How to use ``input-mask-android
`` with [TextInputEditText](https://material.io/develop/android/components/text-input-layout/)?

```xml
<com.google.android.material.textfield.TextInputLayout
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:hint="@string/hint_text">

  <com.google.android.material.textfield.TextInputEditText
      android:layout_width="match_parent"
      android:layout_height="wrap_content"/>

</com.google.android.material.textfield.TextInputLayout>
```
Are these two compatible?

**Comment by taflanidi** [comment]
Hey, @omidraha, thanks for your question.

AFAIR, `TextInputEditText` is an `EditText`, meaning it has the same watchers as the regular `EditText`. Thus, our library's `TextWatcher` should be compatible.
