### ISSUE TITLE
How to get the first editable index in the mask?

### ISSUE THREAD

**Issue by MahdiAstanei** [RedMadRobot/input-mask-android#77]
### My Issue:

I want to disable deleting when the user reached to non-removable prefix and for that first, I need to:
  * Detect first editable index in the mask
  * Prevent user to delete when deleting reaches to that index

**Comment by taflanidi** [comment]
Hey @MahdiAstanei, thanks for your question.

Everything outside square brackets pretty much counts as «non-removable», so you simply count every character before first `[` except `{` and `}`, disregarding bracket [escaping](https://github.com/RedMadRobot/input-mask-android/wiki/1.-Mask-Syntax#character-escaping).

As of preventing user to delete this prefix, please look into the [`afterTextChanged()`](https://github.com/RedMadRobot/input-mask-android/blob/master/inputmask/src/main/kotlin/com/redmadrobot/inputmask/MaskedTextChangedListener.kt#L173) method, where the editing actually happens. From there you may override the `afterText` and the `caretPosition` according to your needs.

**Comment by MahdiAstanei** [comment]
It's very helpful, thank you @taflanidi for your response and your nice library

**Comment by taflanidi** [comment]
I'm glad to help.

P.s. `<rant>`I need to write this down somewhere in our guidelines, that the original issue opener is the one who ought to close the resolved issue. NVM`</rant>`
