### ISSUE TITLE
Wrong result

### ISSUE THREAD

**Issue by sm2017** [RedMadRobot/input-mask-android#78]
### Prerequisites

* [x] Put an `X` between the brackets on this line if you have done all of the following:
  * read our [Wiki](https://github.com/RedMadRobot/input-mask-android/wiki);
  * read the entire [Known issues](https://github.com/RedMadRobot/input-mask-android#knownissues) section;
  * checked that my issue isn't already [filled](https://github.com/RedMadRobot/input-mask-android/issues?q=is%3Aissue);
  * searched StackOverflow's [`input-mask`](https://stackoverflow.com/questions/tagged/input-mask) tag for similar problems.

### Describe the bug
I am using https://www.npmjs.com/package/react-native-text-input-mask that use `input-mask-android` as it's core , I have issue with mask `[________]-[____]-[____]-[____]-[____________]`

### Steps to reproduce the behaviour:

I use mask `[________]-[____]-[____]-[____]-[____________]` for uuid mask , but when I type 2 char , cursor jumps to first location, i.e. you want type `hfd50437-64d8-488e-9da2-e6f450c98626` , you type `Hfd5` but result is `D5Hf`

**Expected behaviour**
When you type  you type `Hfd5` result must be `Hfd5`

**Screenshots**

**Platform information**
 - OS version: Android 8
 - Library version: https://www.npmjs.com/package/react-native-text-input-mask@0.8.0

**Comment by taflanidi** [comment]
Hey @sm2017,  
While reading our known issues section, it seems that you've totally missed [this one](https://github.com/RedMadRobot/input-mask-android#inputmask-vs-autocorrection--prediction), which sounds _exactly_ like your bug description. Please go ahead and check it out!

This library you've mentioned is heavily outdated. For instance, see this [pull request](https://github.com/react-native-community/react-native-text-input-mask/pull/85).  
Our "core" has already reached v.4, while you are probably using `2.3.0`.

IMO, it's completely up to you to <strike>kick</strike> gently remind the library [maintainer](https://github.com/ivanzotov) about updating the internals.

**Comment by sm2017** [comment]
@taflanidi OK , thank you
