### ISSUE TITLE
too many methods 5871

### ISSUE THREAD

**Issue by maxim-pandra** [RedMadRobot/input-mask-android#8]
http://www.methodscount.com/?lib=com.redmadrobot%3Ainputmask%3A1.0.0
shows that the total method count is 5871.
Isn't it too much for utility library?

**Comment by Fi5t** [comment]
Yes, you're right. Wait for fix please.

**Comment by xanderblinov** [comment]
Library has kotlin runtime in dependencies. It will be removed in next versions. 

Total method count without kotlin runtime is 202
