### ISSUE TITLE
Date validation when data mask applied

### ISSUE THREAD

**Issue by Madina-S** [RedMadRobot/input-mask-android#82]
### Prerequisites

* [ ] Put an `X` between the brackets on this line if you have done all of the following:
  * read our [Wiki](https://github.com/RedMadRobot/input-mask-android/wiki);
  * read the entire [Known issues](https://github.com/RedMadRobot/input-mask-android#knownissues) section;
  * checked that my feature request isn't already [filled](https://github.com/RedMadRobot/input-mask-android/issues);
  * searched StackOverflow's [`input-mask`](https://stackoverflow.com/questions/tagged/input-mask) tag for similar problems.

### Summary
One paragraph explanation of the feature.

### Motivation
Why are we doing this? What use cases does it support? What is the expected outcome?

### Describe alternatives you've considered
A clear and concise description of the alternative solutions you've considered. Be sure to explain why existing customizability isn't suitable for this feature.

**Comment by taflanidi** [comment]
Do you speak English, @Madina-S?
