### ISSUE TITLE
The mask won't work when set android:textAllCaps as true

### ISSUE THREAD

**Issue by li2** [RedMadRobot/input-mask-android#85]
Firstly thanks for your effort on this great lib.

I encountered a weird issue, the mask is not working and the cursor is always in the first position. see attached image.

Firstly, I thought it was an issue with TextInputEditText, so I reverted my codes to use EditText, the issue is still there, then I clone your sample code and compared line by line by removing different codes in my project.

Finally, I found the issue was caused by `android:textAllCaps="true"`, because it was applied in a style throughout the App, so it's really hard to find it.

            android:digits="1234567890/ "
            android:textAllCaps="true" // Simply add this line in your sample code can replicate this issue.
            android:inputType="number" />

![image](https://user-images.githubusercontent.com/6058601/59889911-fbb7ea80-9411-11e9-98d0-cd929152e701.png)

Hopefully, this can be mentioned in README. Thanks

**Comment by taflanidi** [comment]
Hey @li2!
Please accept my deep appreciation for your issue report.

I've added a [new section](https://github.com/RedMadRobot/input-mask-android#inputmask-vs-androidtextallcaps) to our known issues. Please let me know if you have anything to add, otherwise lets  close this issue!

**Comment by li2** [comment]
Hey @taflanidi 
Thanks for your quick response and the new section you just added is really helpful, appreciate!
