### ISSUE TITLE
When wrong (non-declared in the mask symbols) are input, multiple spaces are inserted instead

### ISSUE THREAD

**Issue by antsher** [RedMadRobot/input-mask-android#90]
### Describe the bug
When wrong (non-declared in the mask symbols) are input, multiple spaces are inserted instead

### Steps to reproduce the behaviour:
1. Have the following mask: "[AA00]  [----]  [----]  [----]  [----]  [----]  [----]  [----]  [---]"
2. Set following input type for the view: "textCapSentences"
3. Set that mask for the view
4. Input wrong characters after the first mask block: for example, SE32 and then ')' character

**Expected behaviour**
Nothing is shown in the view

**Actual behaviour**
Multiple spaces are added

**Platform information**
 - Android 9
 - 4.3.2 and 5.0.0
 - Nokia 6.1

**Comment by taflanidi** [comment]
Hey @antsher, thanks for your report.
I'll look into this a little bit later, please stay tuned.

Meanwhile, could you please try replacing the optional alphanumeric `-` with a mandatory alphanumeric `_` and let me know what happens.

My guess is, it has something to do with the autosuggestion. Force turning it off might solve the issue, but I haven't dug into this yet.

**Comment by antsher** [comment]
Hi @taflanidi
Thanks a lot for the suggestion to replace alphanumeric - with a mandatory alphanumeric _. It actually solved my problem in this case, since wrong numbers are not replaced with spaces any more.

**Comment by taflanidi** [comment]
Please make sure you've understood our documentation correctly.

According to our Wiki, [optional symbols](https://github.com/RedMadRobot/input-mask-android/wiki/1.-Mask-Syntax#optional-symbols) are meant to represent **ranges**, and they are meant to be used together with the mandatory symbols.

**Comment by antsher** [comment]
@taflanidi Ok then, I will close this one since it's not a bug
