### ISSUE TITLE
rightToLeft does not work properly

### ISSUE THREAD

**Issue by Madina-S** [RedMadRobot/input-mask-android#95]
val listener = MaskedTextChangedListener.installOn(
        this,
        "[000] [000] [000]",
        emptyList(),
        AffinityCalculationStrategy.WHOLE_STRING
    )
    listener.rightToLeft = true

I tried all affinity calculation strategies.

But, when the length of the text reaches the maximum, the first character is deleted and the new is inserted to the end. Version is 5.0.0.

**Comment by taflanidi** [comment]
Hey @Madina-S,
Thanks for your report.

This behaviour is intended. 

Let me show you using an example. Imagine you paste a long text into a field with a known character limit. You'd expect the field to allow pasting the text, but then you'd expect it to show error or to cut the excess of the text.

Our library is not for displaying error messages, thus it simply cuts the excessive text.

Now imagine you paste a long string into a right-to-left text field with a known character limit. You'd expect it to cut the text, but this time the actual string ending is on the other side, regardless of the writing direction.

```
limit = 11

lrow ,olleH
```

The same thing happens to your row of digits.
